#%RAML 1.0 Library

traits:
  requireCorrelationId:
    headers:
      x-correlation-id:
        type: string
        required: true
        description: Correlation ID for tracking requests across services

  errorHandling:
    responses:
      400:
        description: Bad Request
        body:
          application/json:
            type: types.ErrorResponse
            example: !include ../examples/error-response-example.json
      404:
        description: Not Found
        body:
          application/json:
            type: types.ErrorResponse
            example: !include ../examples/error-response-example.json
      500:
        description: Internal Server Error
        body:
          application/json:
            type: types.ErrorResponse
            example: !include ../examples/error-response-example.json
